### PR TITLE
Clarify airtable access

### PR DESCRIPTION
**Pull request by choldgraf**
I noticed that @damianavila asked for and received write access to the AirTable. We currently are keeping the AirTable to one account with edit permissions, and share that account via BitWarden. Otherwise, each person we add with editing permissions will incur an extra $22/month charge, and at least right now I don't see the value in having many people with separate editing privileges on top of a shared account.

This PR tries to clarify this!

### CODE REVIEW

**Review by damianavila — APPROVED** [review]
Thanks for the clarification, @choldgraf!

**Comment by damianavila** [comment]
> I noticed that @damianavila asked for and received write access to the AirTable. 

Should you remove the write access I now have so we can save those 22 USD/month charge, @choldgraf?

**Comment by choldgraf** [comment]
Thanks @damianavila - and yep, that should now be done

**Comment by damianavila** [comment]
> and yep, that should now be done

Is that tracked somewhere, if not can you confirm that happened? Otherwise, we are going to forget it.

**Comment by choldgraf** [comment]
Already completed 👍

**Comment by damianavila** [comment]
Thanks for the confirmation!!

**Pull request merged**
