### PR TITLE
Update the onboarding issue template

### PR DESCRIPTION
**Pull request by GeorgianaElena**
I'll keep this PR open while we onboard Pris in https://github.com/2i2c-org/team-compass/issues/651 to update any missing info we discover in the process

### CODE REVIEW

**Comment by consideRatio** [comment]
@GeorgianaElena I've added a lot of more fine detail notes in https://github.com/2i2c-org/team-compass/issues/651.

I'll keep editing that issue and once we're done, I figure we can add such updates here as well.

**Comment by consideRatio** [comment]
Thank you @GeorgianaElena! Can you re-word the commit message to not `@mention` me as that triggers a lot of pings whenever for example someone would rebase that commit or similar somewhere in a fork.

**Comment by GeorgianaElena** [comment]
> Can you re-word the commit message to not @mention me as that triggers a lot of pings 

Ops, yes, sorry about that.

@consideRatio, I've rebased this, and changed it based on your notes in https://github.com/2i2c-org/team-compass/issues/651 and the comments there. Please feel free to add to this PR the things that still seem to be missing?

**Review by consideRatio — APPROVED** [review]
Excellent I see that you also got the calendar part there, further clarity on how to fix 2i2c google accounts, and fixed misc typos I've made!

Let's go for a merge here and do another iteration in the future.

**Pull request merged**
