### PR TITLE
Add invoicing procedures

### PR DESCRIPTION
**Pull request by choldgraf**
This adds some basic instructions for sending invoices to CS&S, including the admin addresses to cc on the invoice.

cc @consideRatio - would this have been enough information for you? Or perhaps we should link out to the CS&S invoicing docs too?

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
- CS&S have documentation on how to provide invoices that is worth linking out to.
- The grant code. Who decides what code to use / who to contact about it in 2i2c, and/or where to read about them? It could be good if there is a link to help 2i2c admins making such call to find their way to such document directly from here, if there is a grant code document to link to or similar.

**Comment by damianavila** [comment]
> The grant code. Who decides what code to use / who to contact about it in 2i2c, and/or where to read about them? It could be good if there is a link to help 2i2c admins making such call to find their way to such document directly from here, if there is a grant code document to link to or similar.

This is a very good point raised by @consideRatio.

**Comment by choldgraf** [comment]
We actually ran into the same issue over in this PR:

- https://github.com/2i2c-org/team-compass/pull/659

So I've added a link to these docs that cross-references the "how to find my grant code" section. I'll merge this one since I think @consideRatio 's comments are now addressed!

**Review by damianavila — APPROVED** [review]

**Comment by choldgraf** [comment]
One sec actually, I'm gonna move some of the "invoicing instructions" docs that were in reimbursements back into "invoices" and cross-link from there. That's a more natural space I think

**Comment by choldgraf** [comment]
ok now done + merged!

**Comment by consideRatio** [comment]
Wieee thanks @choldgraf!!

**Pull request merged**
