### PR TITLE
Testing hidden folders with RTD

### PR DESCRIPTION
**Pull request by choldgraf**
This is just me playing around with [staticrypt](https://github.com/robinmoisson/staticrypt) to learn more about it.

I think I _may_ have found a bug in RTD? I opened this one to ask about it:

- https://github.com/readthedocs/readthedocs.org/issues/9797

### CODE REVIEW

**Comment by choldgraf** [comment]
Hmmm for some reason it is correctly finding the HTML, but not actually replacing it with the encrypted version.

https://readthedocs.org/projects/2i2c-team-compass/builds/18882723/

**Comment by humitos** [comment]
📰 We've done some progress on the `build.jobs.post_build` issue. We hope to review that PR (https://github.com/readthedocs/readthedocs.org/pull/9888), merge and deploy in the following weeks. I will try to come back here and comment when it's deployed 😄 . Stay tuned.

**Comment by humitos** [comment]
Hi @choldgraf 👋🏼 . I followed your example to test this out and I got it working at https://test-builds.readthedocs.io/en/staticrypt/ (password is `humitos`). Let me know if this is useful for you 😄

**Comment by choldgraf** [comment]
@humitos it worked!

**Comment by humitos** [comment]
Great! 💯 

I'm curious about what's the use-case behind this idea about using `staticrypt`. Would you like to expand this? 🙏🏼 In particular, in Read the Docs community where it only supports public repositories. So, putting the HTML content behind a password won't avoid people accessing the content anyways.

On the other hand, on Read the Docs for Business, a similar feature is already built-in in the platform: https://docs.readthedocs.io/en/stable/commercial/sharing.html

> If you don't want to share the idea publicly for any reason, please contact me at manuel at readthedocs (.org | .com)

**Comment by choldgraf** [comment]
In our case, I'm auto-generating dashboards about 2i2c's upstream activity as well as some financial activity with Jupyter Book. The data is not publicly accessible, and some of the dashboards might have sensitive information in them. So the source files don't have anything sensitive, but the built outputs do, which is why I wanted to put them behind a password.

**Comment by consideRatio** [comment]
@choldgraf is this a PR to close?

**Comment by choldgraf** [comment]
@consideRatio yeah let's close it, was a little experiment but I'm not sure if/when we'll get to it so we can always re-open if need be

**Pull request closed without merging**
