### PR TITLE
Partnerships: Document how to track hub usage with Grafana

### PR DESCRIPTION
**Pull request by jnywong**
Closes https://github.com/2i2c-org/meta/issues/1080

### CODE REVIEW

**Comment by Gman0909** [comment]
Has anyone had a chance to validate why this failed?

**Comment by sgibson91** [comment]
From [the logs](https://github.com/2i2c-org/team-compass/actions/runs/8878582014/job/24721087815?pr=855#step:5:166), looks like some code in the hub-activity markdown file failed

```
/home/runner/work/team-compass/team-compass/partnerships/community_success/hub-activity.md: WARNING: Executing notebook failed: CellExecutionError [mystnb.exec]
/home/runner/work/team-compass/team-compass/partnerships/community_success/hub-activity.md: WARNING: Notebook exception traceback saved in: /home/runner/work/team-compass/team-compass/_build/dirhtml/reports/partnerships/community_success/hub-activity.err.log [mystnb.exec]
```

**Comment by jnywong** [comment]
I am taking a closer look at this, currently trying to replicate this in my local development environment.

**Comment by jnywong** [comment]
Closing this PR since GitHub secrets are not available in a forked repo. Superseded by https://github.com/2i2c-org/team-compass/pull/859

**Pull request closed without merging**
