### PR TITLE
Support process lead by Engineering.

### PR DESCRIPTION
**Pull request by damianavila**
This change actually documents in our team compass the agreement we achieved as described in https://github.com/2i2c-org/team-compass/issues/655.

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
LGTM, thank you @damianavila!!

I think this is agreed on elsewhere and it makes sense to go for a quick merge!

**Comment by choldgraf** [comment]
A quick thought here - I think that it'd be helpful if we kept the "scope and responsibilities" section of each area as a single source of truth for what they're responsible for. So I suggest that we add a short section there for engineering, and it can just delegate + link to these support docs for more information.

**Comment by damianavila** [comment]
I agree, I will do that once the big refactor PR lands so you don't have to deal with conflicts on that one.

**Comment by damianavila** [comment]
> I agree, I will do that once the big refactor PR lands so you don't have to deal with conflicts on that one.

See https://github.com/2i2c-org/team-compass/pull/680.

**Pull request merged**
